# Generated by Django 6.1.1 on 2026-09-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='motif_validation',
            field=models.CharField(blank=True, help_text='Raison de la validation manuelle (signalements, révocation…)', max_length=200),
        ),
        migrations.AddField(
            model_name='premium',
            name='validation_auto',
            field=models.BooleanField(default=False, help_text="True si validé automatiquement à l'achat (pas de problème détecté)"),
        ),
    ]
