# Generated by Django 6.1.1 on 2026-09-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_premium_motif_validation_premium_validation_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='duree_mois',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
