# Generated by Django 6.1.1 on 2026-10-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_premium_duree_mois'),
    ]

    operations = [
        migrations.AddField(
            model_name='profillivreur',
            name='derniere_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profillivreur',
            name='derniere_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profillivreur',
            name='derniere_position_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
