"""
Django settings for Lebougui project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ux(hiug3v&#xdf=yci0em)&b^t-%e&avada!5u$!!u*p1v8!u4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.ngrok-free.dev',
    '.ngrok.io',
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}


# settings.py
from datetime import timedelta

SIMPLE_JWT = {
    # Durée de vie du jeton d'accès (utilisé pour chaque requête)
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    
    # Durée de vie du jeton de rafraîchissement (utilisé pour obtenir un nouveau jeton d'accès)
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
}





CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'https://*.ngrok-free.dev',
    'https://*.ngrok.io',
]





# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'paiements',
    'commandes',
    'publications',
    'utilisateurs',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Lebougui.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Lebougui.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

from dotenv import load_dotenv
import os
load_dotenv(os.path.join(BASE_DIR, '.env'))

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT')
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

AUTHENTICATION_BACKENDS = [
    'utilisateurs.backends.HybridAuthBackend',
    'django.contrib.auth.backends.ModelBackend',  # utile pour l'admin Django
]

AUTH_USER_MODEL = 'utilisateurs.Utilisateur'


IA_SERVICE_URL = "http://127.0.0.1:8001"
# settings.py
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
# Autoriser uniquement votre serveur React Vite
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]



# ============================================================
# PAYDUNYA
# ============================================================
PAYDUNYA_MODE = "test"   # "test" ou "live"

PAYDUNYA_MASTER_KEY = "5bIyo8Sc-Ja1W-KeZr-INqD-BHwiwKBKM6xQ"
PAYDUNYA_PRIVATE_KEY = "test_private_19K74GhfpF5LR1htAJhAyyWBmiD"
PAYDUNYA_PUBLIC_KEY = "test_public_RQQMOWT5hHwKedJgRSj0l6AlHM2"
PAYDUNYA_TOKEN = "2JWGSXxO10S9uLF9izBD"

# URL publique (ngrok) pour que PayDunya puisse appeler le webhook
PAYDUNYA_CALLBACK_URL = "https://quit-overhead-goggles.ngrok-free.dev/api/webhooks/paydunya/"

# URLs de redirection après paiement
PAYDUNYA_RETURN_URL = "http://localhost:5173/acheteur/retour-paiement"
PAYDUNYA_CANCEL_URL = "http://localhost:5173/acheteur/panier"