# Generated by Django 6.1.1 on 2026-09-13 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('audio', models.FileField(upload_to='publications/audio/')),
                ('texte_transcrit', models.TextField(blank=True)),
                ('texte_traduit', models.TextField(blank=True)),
                ('score_confiance_ia', models.FloatField(blank=True, null=True)),
                ('statut_moderation', models.CharField(choices=[('visible', 'Visible'), ('en_attente', 'En attente de validation admin'), ('rejete', "Rejeté par l'admin")], default='en_attente', max_length=15)),
                ('adresse', models.CharField(max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('pecheur', models.ForeignKey(limit_choices_to={'role': 'pecheur'}, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publications.publication')),
                ('description', models.TextField()),
            ],
            bases=('publications.publication',),
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publications.publication')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('poisson', 'Poisson'), ('fruit_de_mer', 'Fruit de mer')], max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=8)),
                ('media', models.FileField(upload_to='publications/media/')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('rupture', 'Rupture de stock')], default='disponible', max_length=15)),
            ],
            bases=('publications.publication',),
        ),
    ]
