# Generated by Django 6.1.1 on 2026-09-15 21:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publications', '0001_initial'),
        ('utilisateurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_poisson', models.CharField(help_text='Nom du produit surveillé (ex: Thiof, Capitaine, Crevettes)', max_length=100)),
                ('zone', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('acheteur', models.ForeignKey(limit_choices_to={'role': 'acheteur'}, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('date_limite_confirmation', models.DateTimeField(blank=True, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente_pecheur', 'En attente de confirmation du pêcheur'), ('refusee', 'Refusée par le pêcheur'), ('annulee', "Annulée par l'acheteur"), ('en_attente_paiement', 'En attente de paiement'), ('payee', 'Payée'), ('en_recherche_livreur', "En recherche d'un livreur"), ('en_livraison', 'En cours de livraison'), ('livree', 'Livrée')], default='en_attente_pecheur', max_length=30)),
                ('acheteur', models.ForeignKey(limit_choices_to={'role': 'acheteur'}, on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL)),
                ('pecheur', models.ForeignKey(limit_choices_to={'role': 'pecheur'}, on_delete=django.db.models.deletion.CASCADE, related_name='commandes_recues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', "En attente d'un livreur"), ('acceptee', 'Acceptée par le livreur'), ('en_cours', 'En cours'), ('livree', 'Livrée')], default='en_attente', max_length=30)),
                ('tarif_livraison', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('itineraire', models.JSONField(blank=True, null=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('commandes', models.ManyToManyField(related_name='livraisons', to='commandes.commande')),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='utilisateurs.profillivreur')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etoile', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(limit_choices_to={'role': 'acheteur'}, on_delete=django.db.models.deletion.CASCADE, related_name='notes_redigees', to=settings.AUTH_USER_MODEL)),
                ('cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_recues', to=settings.AUTH_USER_MODEL)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='commandes.commande')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=8)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commandes.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='publications.produit')),
            ],
        ),
    ]
