# Generated by Django 6.1.1 on 2026-09-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='adresse_livraison',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='commande',
            name='latitude_livraison',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='longitude_livraison',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
