# Generated by Django 6.1.1 on 2026-09-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_commande_adresse_livraison_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='paydunya_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
