# Generated by Django 6.1.1 on 2026-09-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_commande_paydunya_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='date_acceptation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='date_recuperation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='position_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='position_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='position_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('disponible', "Disponible (personne ne l'a prise)"), ('acceptee', 'Acceptée par le livreur'), ('en_recuperation', 'Le livreur est au quai'), ('en_livraison', 'Le livreur est en route vers le client'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='disponible', max_length=30),
        ),
    ]
