# Generated by Django 6.1.1 on 2026-09-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_livraison_date_acceptation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('acceptee', 'Acceptée par le livreur'), ('en_recuperation', 'Le livreur est au quai'), ('en_livraison', 'Le livreur est en route vers le client'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='acceptee', max_length=30),
        ),
    ]
