# Generated by Django 6.1.1 on 2026-09-24 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0005_alter_livraison_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='action_prise',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='note',
            name='date_traitement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='traite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='traite_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_traites', to=settings.AUTH_USER_MODEL),
        ),
    ]
