# Generated by Django 6.1.1 on 2026-09-24 23:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0006_note_action_prise_note_date_traitement_note_traite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('auteur', 'commande', 'cible')},
        ),
    ]
